# Generated by Django 5.2.8 on 2025-12-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='colaborador',
            field=models.BooleanField(default=False),
        ),
    ]
