# Generated by Django 5.2.8 on 2025-12-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_articulo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=100)),
                ('contenido', models.TextField(max_length=5000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='articulos/')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(blank=True, max_length=50, null=True)),
                ('contenido', models.TextField(max_length=1000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
