# Generated by Django 5.2.8 on 2025-11-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id_articulo', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('titulo', models.TextField(max_length=50)),
                ('subtitulo', models.TextField(max_length=100)),
                ('contenido', models.TextField(max_length=5000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
