# Generated by Django 5.2.8 on 2025-11-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='id_articulo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
