# Generated by Django 5.2.8 on 2025-11-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0002_alter_articulo_id_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='subtitulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
