# Generated by Django 5.2.8 on 2025-11-27 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0003_alter_articulo_subtitulo_alter_articulo_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(blank=True, max_length=50, null=True)),
                ('contenido', models.TextField(max_length=1000)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='mi_primer_app.articulo')),
            ],
        ),
    ]
