# Generated by Django 5.2.8 on 2025-11-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_primer_app', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
    ]
